@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 07 14:32:20 +0200 2023
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim FourDigitLEDdriverText_tb_behav -key {Behavioral:sim_3:Functional:FourDigitLEDdriverText_tb} -tclbatch FourDigitLEDdriverText_tb.tcl -view C:/Users/athanasi/Documents/GitHub/digital-circuit-lab/project_1/FourDigitLEDdriverText_tb_func_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
