webtalk_init -webtalk_dir C:/Users/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_3/behav/xsim/xsim.dir/uart_receiver_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec 10 21:49:53 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "efbd0901-d633-4197-97b8-f63439680e76" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d5894e8e3316436a9d12ab5bf4f946c0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "270" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-6300 Six-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3512 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "701 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14036_KB" -context "xsim\\usage"
webtalk_transmit -clientid 438771275 -regid "" -xml C:/Users/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_3/behav/xsim/xsim.dir/uart_receiver_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_3/behav/xsim/xsim.dir/uart_receiver_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_3/behav/xsim/xsim.dir/uart_receiver_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
