webtalk_init -webtalk_dir /home/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_2/impl/timing/xsim/xsim.dir/uart_transmitter_tb_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 28 20:05:20 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8084ca02-0896-4ce7-9dd3-f305be23846a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d5894e8e3316436a9d12ab5bf4f946c0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 12 (bookworm)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "901.549 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "20.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "472 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "89 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2224" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "123" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.97_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "260184_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1906881246 -regid "" -xml /home/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_2/impl/timing/xsim/xsim.dir/uart_transmitter_tb_time_impl/webtalk/usage_statistics_ext_xsim.xml -html /home/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_2/impl/timing/xsim/xsim.dir/uart_transmitter_tb_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm /home/athanasi/Documents/GitHub/digital-circuit-lab/project_2/project_2.sim/sim_2/impl/timing/xsim/xsim.dir/uart_transmitter_tb_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
